project_id = "usgqtqadoqzyfttjazmz"

[functions.send-verification-code]
verify_jwt = false

[functions.verify-registration-code]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[functions.chatbot-assistant]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-help-email]
verify_jwt = false

[functions.send-registration-email]
verify_jwt = false

[functions.community-ai-responder]
verify_jwt = false

[functions.notify-brillarte-new-post]
verify_jwt = false

[functions.send-newsletter-subscription]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.chat-ai-responder]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.agent-support]
verify_jwt = false

[functions.ticket-ai-response]
verify_jwt = false

[functions.lookup-email-by-code]
verify_jwt = false

[functions.send-credit-notification]
verify_jwt = false

[functions.send-abandoned-cart-email]
verify_jwt = false

[functions.verify-pickup-request]
verify_jwt = false

[functions.send-address-change-email]
verify_jwt = false

[functions.send-order-tracking-help]
verify_jwt = false

[functions.send-order-request-confirmation]
verify_jwt = false

[functions.generate-promo-notification]
verify_jwt = false

[functions.notify-mention]
verify_jwt = false

[functions.manage-payment-codes]
verify_jwt = false

[functions.send-chat-summary]
verify_jwt = false

[functions.notify-urgent-case]
verify_jwt = false

[functions.ai-product-creator]
verify_jwt = false

[functions.create-user-account]
verify_jwt = false
