project_id = "gzyfcunlbrfcnbxxaaft"

[functions.send-confirmation-email]
verify_jwt = false

[functions.verify-pickup-request]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.send-address-change-email]
verify_jwt = false

[functions.send-help-email]
verify_jwt = false

[functions.send-registration-email]
verify_jwt = false