project_id = "usgqtqadoqzyfttjazmz"

[functions.chatbot-assistant]
verify_jwt = false

[functions.agent-support]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-order-tracking-help]
verify_jwt = false

[functions.send-order-request-confirmation]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.verify-pickup-request]
verify_jwt = false
